### PR TITLE
Adds 2nd parameter for calling function to modify Remarked Instance

### PR DESCRIPTION
**Pull request by Charon77**
2nd parameter fnConfigureMd is expected to be a function that receives the Remarked instance.

Do whatever you want with md there _synchronously_

### CODE REVIEW

**Comment by Charon77** [comment]
###### Usage example: Adding plugins

```js
return gulp.src(globMarkdown)
    .pipe(markdown(opts, (md=>{
      md.renderer.rules.heading_open = headingAnchorRendererPlugin
    })))

function headingAnchorRendererPlugin(tokens, idx ) {
  if (tokens[idx+1].type == 'inline') {
    let heading_anchor = slug(tokens[idx+1].content, {lower: true})
    return '<h' + tokens[idx].hLevel + ' id="' + heading_anchor + '">';
  }
  return '<h' + tokens[idx].hLevel + '>';
}
```

**Comment by Charon77** [comment]
@johnotander @charlike 
Any comments?

**Comment by johnotander** [comment]
Sorry for the delay @Charon77. This lgtm, do you mind adding a bit of documentation to the readme? Then I'll get this merged and published.

**Comment by derhuerst** [comment]
@Charon77 friendly ping (:

**Comment by Charon77** [comment]
Ah sorry, I must have missed the notif and didn't see the comments here.

I'll sure do, will keep you posted

**Comment by Charon77** [comment]
@johno Is this alright?

**Comment by johno** [comment]
This is great, thanks!

**Pull request merged**
